version: "3.8"

services:
  panel:
    image: quay.io/pterodactyl/panel:latest
    container_name: pterodactyl_panel
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      APP_URL: http://localhost:8080
      DB_HOST: database
      DB_PORT: 3306
      DB_DATABASE: pterodactyl
      DB_USERNAME: pterodactyl
      DB_PASSWORD: secretpassword
      CACHE_DRIVER: redis
      SESSION_DRIVER: redis
      QUEUE_DRIVER: redis
      REDIS_HOST: redis
    volumes:
      - panel_data:/var/www/html
    depends_on:
      - database
      - redis

  wings:
    image: quay.io/pterodactyl/wings:latest
    container_name: pterodactyl_wings
    restart: unless-stopped
    privileged: true
    network_mode: "host"
    environment:
      WINGS_PANEL: http://localhost:8080
      WINGS_TOKEN: your_wings_token_here
    volumes:
      - wings_data:/etc/pterodactyl
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro

  database:
    image: mariadb:10.5
    container_name: pterodactyl_database
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: pterodactyl
      MYSQL_USER: pterodactyl
      MYSQL_PASSWORD: secretpassword
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:alpine
    container_name: pterodactyl_redis
    restart: unless-stopped
    volumes:
      - redis_data:/data

volumes:
  panel_data:
  wings_data:
  db_data:
  redis_data:
