version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: dolibarr
      APP_PORT: 80

  mariadb:
    image: mariadb:10.9.4
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dolibarr
      MYSQL_USER: user
      MYSQL_PASSWORD: root
    volumes:
      - db-data:/var/lib/mysql

  dolibarr:
    image: dolibarr/dolibarr:latest
    restart: unless-stopped
    depends_on:
      - mariadb
    environment:
      DOLI_DB_HOST: mariadb
      DOLI_DB_NAME: dolibarr
      DOLI_DB_USER: user
      DOLI_DB_PASSWORD: root
    volumes:
      - dolibarr-data:/var/www/html

volumes:
  db-data:
  dolibarr-data:
