version: "3.8"

services:
  db:
    image: mariadb:10.5
    container_name: roundcube-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword123
      MYSQL_DATABASE: roundcube
      MYSQL_USER: roundcube
      MYSQL_PASSWORD: roundcubepass123
    volumes:
      - roundcube-db-data:/var/lib/mysql

  roundcube:
    image: roundcube/roundcubemail:latest
    container_name: roundcube-web
    depends_on:
      - db
    ports:
      - "8080:80"  # accessible sur http://ton-ip:8080
    restart: unless-stopped
    environment:
      ROUNDCUBEMAIL_DEFAULT_HOST: "ssl://imap.tonserveurmail.com"
      ROUNDCUBEMAIL_SMTP_SERVER: "tls://smtp.tonserveurmail.com"
      ROUNDCUBEMAIL_DES_KEY: "someRandomStringHere1234567890"  # clé secrète pour la session
      ROUNDCUBEMAIL_DB_TYPE: "mysql"
      ROUNDCUBEMAIL_DB_HOST: "db"
      ROUNDCUBEMAIL_DB_USER: "roundcube"
      ROUNDCUBEMAIL_DB_PASSWORD: "roundcubepass123"
      ROUNDCUBEMAIL_DB_NAME: "roundcube"
    volumes:
      - roundcube-data:/var/www/html

volumes:
  roundcube-db-data:
  roundcube-data:
