version: "3.8"

services:
  mariadb:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: erpnext
      MYSQL_USER: erpnext
      MYSQL_PASSWORD: erpnextpassword
    volumes:
      - erpnext_mariadb:/var/lib/mysql
    restart: unless-stopped

  redis_cache:
    image: redis:6-alpine
    command: redis-server --appendonly yes
    volumes:
      - erpnext_redis_cache:/data
    restart: unless-stopped

  redis_queue:
    image: redis:6-alpine
    command: redis-server --appendonly yes
    volumes:
      - erpnext_redis_queue:/data
    restart: unless-stopped

  redis_socketio:
    image: redis:6-alpine
    command: redis-server --appendonly yes
    volumes:
      - erpnext_redis_socketio:/data
    restart: unless-stopped

  erpnext:
    image: frappe/erpnext:v15.72.2
    depends_on:
      - mariadb
      - redis_cache
      - redis_queue
      - redis_socketio
    environment:
      SITE_NAME: erp.example.com
      DB_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: rootpassword
      ADMIN_PASSWORD: admin123
      INSTALL_APPS: erpnext
      REDIS_CACHE: redis_cache:6379
      REDIS_QUEUE: redis_queue:6379
      REDIS_SOCKETIO: redis_socketio:6379
    volumes:
      - erpnext_sites:/home/frappe/frappe-bench/sites
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.erpnext.rule=Host(`erpnext.local.umbrel`) || PathPrefix(`/apps/erpnext`)"
      - "traefik.http.services.erpnext.loadbalancer.server.port=8000"

volumes:
  erpnext_mariadb:
  erpnext_redis_cache:
  erpnext_redis_queue:
  erpnext_redis_socketio:
  erpnext_sites:
