version: "3.7"

services:
  erpnext:
    image: frappe/erpnext  # image officielle ERPNext
    restart: always
    volumes:
      - ${APP_DATA_DIR}/sites:/home/frappe/frappe-bench/sites
      - ${APP_DATA_DIR}/logs:/home/frappe/frappe-bench/logs
    ports:
      - "8000:8000"  # Port web d'ERPNext
    environment:
      SITE_NAME: site1.local
      DB_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: erpnext-56881-vllkg  # change le !
      ADMIN_PASSWORD: admin_password_12898hg58fdgh2g855gthgsm          # change le aussi !
