version: "3.7"

services:
  mariadb:
    image: mariadb:10.5
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: erpnext
      MYSQL_PASSWORD: erpnextpassword
      MYSQL_DATABASE: erpnext
    volumes:
      - erpnext-db-data:/var/lib/mysql

  erpnext:
    image: frappe/erpnext
    restart: unless-stopped
    depends_on:
      - mariadb
    environment:
      DB_HOST: mariadb
      DB_PORT: 3306
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: erpnext
      MYSQL_PASSWORD: erpnextpassword
      MYSQL_DATABASE: erpnext
      SITE_NAME: erp.example.com
      ADMIN_PASSWORD: admin123
      INSTALL_APPS: erpnext
    ports:
      - "8000:8000"
    volumes:
      - erpnext-sites:/home/frappe/frappe-bench/sites
    entrypoint: ["/entrypoint.sh"]

volumes:
  erpnext-db-data:
  erpnext-sites:
